config/routes.rb
Rails.application.routes.draw do
  get '/siege' => 'static#home_s'

  get '/bloodborne' => 'static#home_b'

  get '/other' => 'static#home_o'

  get 'static/contact_us'

  get '/siege/operators' => 'operators#index'

  get '/siege/guns' => 'guns#index'

  get '/siege/general' => 'static#general_tips'

  get '/siege/guns/o/:organization' => 'guns#organization_search'

  get '/siege/guns/t/:weapon_type' => 'guns#type_search'

  get '/siege/operators/o/:organization' => 'operators#organization_search'

  get '/siege/operators/c/:main_catagory' => 'operators#main_catagory_search'

  get '/siege/operators/s/:speed' => 'operators#speed_search'

  get '/siege/operators/a/:armor' => 'operators#armor_search'

  get '/siege/guns/:id' => 'guns#show', as: :siege_gun

  get '/siege/operators/:id' => 'operators#show', as: :siege_operator

  get '/about' => 'static#contact_us'

  resources :guns
  resources :operators
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'static#enter'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/gun.rb
class Gun < ApplicationRecord
  has_many :gun_ops
  has_many :operators, through: :gun_ops, source: :operator
end

app/models/gun_op.rb
class GunOp < ApplicationRecord
  belongs_to :gun
  belongs_to :operator
end

app/models/operator.rb
class Operator < ApplicationRecord
  has_many :gun_ops
  has_many :guns, through: :gun_ops
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/gun_op_controller.rb
class GunOpController < ApplicationController
end

app/controllers/guns_controller.rb
class GunsController < ApplicationController
  before_action :set_gun, only: [:show, :edit, :update, :destroy]

  # GET /guns
  # GET /guns.json
  def index
    @guns = Gun.all
  end

  # GET /guns/1
  # GET /guns/1.json
  def show
  end

  # GET /guns/new
  def new
    @gun = Gun.new
  end

  # GET /guns/1/edit
  def edit
  end

  # POST /guns
  # POST /guns.json
  def create
    @gun = Gun.new(gun_params)

    respond_to do |format|
      if @gun.save
        format.html { redirect_to @gun, notice: 'Gun was successfully created.' }
        format.json { render :show, status: :created, location: @gun }
      else
        format.html { render :new }
        format.json { render json: @gun.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /guns/1
  # PATCH/PUT /guns/1.json
  def update
    respond_to do |format|
      if @gun.update(gun_params)
        format.html { redirect_to @gun, notice: 'Gun was successfully updated.' }
        format.json { render :show, status: :ok, location: @gun }
      else
        format.html { render :edit }
        format.json { render json: @gun.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /guns/1
  # DELETE /guns/1.json
  def destroy
    @gun.destroy
    respond_to do |format|
      format.html { redirect_to guns_url, notice: 'Gun was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def organization_search
    @guns = Gun.where( organization: params[:organization] )
    render template: 'guns/index'
  end

  def type_search
    @guns = Gun.where( weapon_type: params[:weapon_type] )
    render template: 'guns/index'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gun
      @gun = Gun.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def gun_params
      params.require(:gun).permit(:damage, :damage_supp, :rate_of_fire, :mobility, :mag_size, :max_ammo_pvp, :max_ammo_th)
    end
end

app/controllers/operators_controller.rb
class OperatorsController < ApplicationController
  before_action :set_operator, only: [:show, :edit, :update, :destroy]

  # GET /operators
  # GET /operators.json
  def index
    @operators = Operator.all
  end

  # GET /operators/1
  # GET /operators/1.json
  def show
    @guns = Gun.all
  end

  # GET /operators/new
  def new
    @operator = Operator.new
  end

  # GET /operators/1/edit
  def edit
  end

  # POST /operators
  # POST /operators.json
  def create
    @operator = Operator.new(operator_params)

    respond_to do |format|
      if @operator.save
        format.html { redirect_to @operator, notice: 'Operator was successfully created.' }
        format.json { render :show, status: :created, location: @operator }
      else
        format.html { render :new }
        format.json { render json: @operator.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /operators/1
  # PATCH/PUT /operators/1.json
  def update
    respond_to do |format|
      if @operator.update(operator_params)
        format.html { redirect_to @operator, notice: 'Operator was successfully updated.' }
        format.json { render :show, status: :ok, location: @operator }
      else
        format.html { render :edit }
        format.json { render json: @operator.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /operators/1
  # DELETE /operators/1.json
  def destroy
    @operator.destroy
    respond_to do |format|
      format.html { redirect_to operators_url, notice: 'Operator was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def organization_search
    @operators = Operator.where( organization: params[:organization] )
    render template: 'operators/index'
  end

  def main_catagory_search
    @operators = Operator.where( main_catagory: params[:main_catagory] )
    render template: 'operators/index'
  end

  def speed_search
    @operators = Operator.where( speed: params[:speed] )
    render template: 'operators/index'
  end

  def armor_search
    @operators = Operator.where( armor: params[:armor] )
    render template: 'operators/index'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_operator
      @operator = Operator.find(params[:id])
    end


    # Never trust parameters from the scary internet, only allow the white list through.
    def operator_params
      params.require(:operator).permit(:pick_rate, :win_rate, :kda)
    end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def home_s
  end

  def home_b
  end

  def home_o
  end

  def enter
  end

  def contact_us
  end

  def general_tips
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def body_class
    case request.env['PATH_INFO']
      when "/" then "home"
      when "/bloodborne" then "bloodborne"
    else
      ""
    end
  end
end

app/helpers/gun_op_helper.rb
module GunOpHelper
end

app/helpers/guns_helper.rb
module GunsHelper
end

app/helpers/operators_helper.rb
module OperatorsHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/views/guns/_form.html.erb
<%= form_with(model: gun, local: true) do |form| %>
  <% if gun.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(gun.errors.count, "error") %> prohibited this gun from being saved:</h2>

      <ul>
      <% gun.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :damage %>
    <%= form.text_field :damage, id: :gun_damage %>
  </div>

  <div class="field">
    <%= form.label :damage_supp %>
    <%= form.text_field :damage_supp, id: :gun_damage_supp %>
  </div>

  <div class="field">
    <%= form.label :rate_of_fire %>
    <%= form.text_field :rate_of_fire, id: :gun_rate_of_fire %>
  </div>

  <div class="field">
    <%= form.label :mobility %>
    <%= form.text_field :mobility, id: :gun_mobility %>
  </div>

  <div class="field">
    <%= form.label :mag_size %>
    <%= form.text_field :mag_size, id: :gun_mag_size %>
  </div>

  <div class="field">
    <%= form.label :max_ammo_pvp %>
    <%= form.text_field :max_ammo_pvp, id: :gun_max_ammo_pvp %>
  </div>

  <div class="field">
    <%= form.label :max_ammo_th %>
    <%= form.text_field :max_ammo_th, id: :gun_max_ammo_th %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/guns/edit.html.erb
<h1>Editing Gun</h1>

<%= render 'form', gun: @gun %>

<%= link_to 'Show', @gun %> |
<%= link_to 'Back', guns_path %>

app/views/guns/index.html.erb
<p id="notice"><%= notice %></p>

<h1 style="text-decoration: underline; text-align: center; margin-bottom: 50px;">Search Weapons</h1>

<div class="search">
  <h3 style="margin-top: 0;">CTU</h3>
  <ul>
    <% @guns.find_by_sql("SELECT DISTINCT organization FROM guns ORDER BY organization").each do |gun| %>
    <a href="/siege/guns/o/<%= gun.organization %>"><li><%= gun.organization %></li></a>
    <% end %><br />
  </ul>
  <h3 style="margin-top: 0;">Weapon Type</h3>
  <ul>
    <% @guns.find_by_sql("SELECT DISTINCT weapon_type FROM guns ORDER BY weapon_type").each do |gun| %>
    <a href="/siege/guns/t/<%= gun.weapon_type %>"><li><%= gun.weapon_type %></li></a>
    <% end %>
  </ul>
</div>

<div class="guns">
  <% @guns.each do |gun| %>
    <%= link_to siege_gun_path(gun), class: "gunLink" do %>
        <div class="gun">
          <div class="hoverEffect"></div>
          <img src="https://s3.us-east-2.amazonaws.com/noob-gaming-assets/<%= gun.name %>.jpg"><br/>
          <br>
          <%= gun.name %>
        </div>
    <% end %>
  <% end %>
</div>

app/views/guns/new.html.erb
<h1>New Gun</h1>

<%= render 'form', gun: @gun %>

<%= link_to 'Back', guns_path %>

app/views/guns/show.html.erb
<p id="notice"><%= notice %></p>
<div class="gunBody">
  <img src="https://s3.us-east-2.amazonaws.com/noob-gaming-assets/<%= @gun.name %>.jpg" class="gunImage" >

  <h1><%= @gun.name %></h1>
  <div class="gunInfo">
    <p>
      <strong>Damage:</strong>
      <%= @gun.damage %>
    </p>

    <p>
      <strong>Rate of fire:</strong>
      <%= @gun.rate_of_fire %>
    </p>

    <p>
      <strong>Mag size:</strong>
      <%= @gun.mag_size %>+ 1
    </p>

    <p>
      <strong>Max ammo (PVP/TH):</strong>
      <%= @gun.max_ammo_pvp %>/<%= @gun.max_ammo_th %>
    </p>
  </div>

  <div class="container">
    <ul class="nav nav-pills" id="tabsMenu">
      <li class="active"><a data-toggle="pill" href="#home"><img src="https://s3.us-east-2.amazonaws.com/noob-gaming-assets/sight.png" class="nav-icon"></a></li>
      <li><a data-toggle="pill" href="#menu1"><img src="https://s3.us-east-2.amazonaws.com/noob-gaming-assets/grip.png" class="nav-icon"></a></li>
      <li><a data-toggle="pill" href="#menu2"><img src="https://s3.us-east-2.amazonaws.com/noob-gaming-assets/barrel.png" class="nav-icon"></a></li>
      <li><a data-toggle="pill" href="#menu3"><img src="https://s3.us-east-2.amazonaws.com/noob-gaming-assets/underbarrel.png" class="nav-icon"></a></li>
    </ul>

    <div class="tab-content">
        <% if @gun.sights %>
        <div id="home" class="tab-pane fade in active">
          <h2>SIGHTS</h2>
        <% JSON.parse(@gun.sights).each do |sight| %>
          <% if sight == "ACOG" %>
            <h4><%= sight %> Sight</h4>
            <ul class="descriptions">Pros
              <li>Good for long range engagements</li>
            </ul>
            <ul class="descriptions">
              Cons
              <li>Hard to use in CQC due to it's zoom. Can distort your view and block angles to the sides.</li>
            </ul>
          <% elsif sight == "Red Dot" %>
            <h4><%= sight %> Sight</h4>
            <ul class="descriptions">
              <li>Pretty basic scope. Gives increased accuracy for medium distance engagements.</li>
            </ul>
            <ul class="descriptions">
              <li>Blocks a good amount of vision in your peripherals and doesn't help much for long distance engagements.</li>
            </ul>
          <% elsif sight == "Reflex" %>
            <h4><%= sight %> Sight</h4>
            <ul class="descriptions">
              Pros
              <li>Allows for the most peripheral vision when in ADS, giving you more knowledge of your surroundings.</li>
            </ul>
            <ul class="descriptions">
              Cons
              <li>They don't help you much in long distance engagements and are sort of weird to look through.</li>
            </ul>
          <% elsif sight == "Holographic" %>
            <h4><%= sight %> Sight</h4>
            <ul class="descriptions">
              <li>One of the best CQC and medium ranged engagements, gives you the most vision and zoom for the least amount of zoom distortion.</li>
            </ul>
            <ul class="descriptions">
              <li>Doesn't help much for long distance engagments.</li>
            </ul>
          <% end %>
        <% end %>
      </div>
      <% else %>
        <div id="home" class="tab-pane fade in active">
          <h2>SIGHTS</h2>
          <h4>No sights available!</h4>
        </div>
      <% end %>
      <% if @gun.grip %>
      <div id="menu1" class="tab-pane fade">
        <h2>GRIP</h2>
        <% JSON.parse(@gun.grip).each do |grip| %>
          <% if grip == "Vertical" %>
            <h4><%= grip %> Grip</h4>
            <ul class="descriptions">
              Pros
              <li>Reduces recoil considerably, allowing you to get more consistent shots.</li>
            </ul>
            <ul class="descriptions">
              Cons
              <li>If this is your only choice, none. If you can take angled sights, it doesn't have the speed angled has going from hip fire to ADS.</li>
            </ul>
          <% elsif grip == "Angled" %>
            <h4><%= grip %> Grip</h4>
            <ul class="descriptions">
              Pros
              <li>Allows for faster transition from hip fire to ADS and back.</li>
            </ul>
            <ul class="descriptions">
              Cons
              <li>Not available on every gun and doesn't have the same effect on recoil as horizontal.</li>
            </ul>
          <% end %>
        <% end %>
      </div>
      <% else %>
      <div id="menu1" class="tab-pane fade">
        <h2>GRIP</h2>
        <h4>No grip available!</h4>
      </div>
      <% end %>
      <% if @gun.barrel %>
      <div id="menu2" class="tab-pane fade">
        <h2>BARREL</h2>
        <% JSON.parse(@gun.barrel).each do |barrel| %>
          <% if barrel == "Suppresor" %>
            <h4><%= barrel %></h4>
            <ul class="descriptions">
              Pros
              <li>Allows for more silent shots and covers your bullet trail.</li>
            </ul>
            <ul class="descriptions">
              Cons
              <li>You lose quite a bit of damage on your weapon and it doesn't help your weapons recoil.</li>
            </ul>
          <% elsif barrel == "Compensator" %>
            <h4><%= barrel %></h4>
            <ul class="descriptions">
              Pros
              <li>Great for reducing recoil when going full auto on a gun.</li>
            </ul>
            <ul class="descriptions">
              Cons
              <li>Doesn't have as great an effect on tab/burst firing.</li>
            </ul>
          <% elsif barrel == "Flash Hider" %>
            <h4><%= barrel %></h4>
            <ul class="descriptions">
              Pros
              <li>Very good at controlling recoil on burt fire.</li>
            </ul>
            <ul class="descriptions">
              Cons
              <li>Doesn't have much effect when you start shooting for extended periods of time.</li>
            </ul>
          <% elsif barrel == "Muzzle Break" %>
            <h4><%= barrel %></h4>
            <ul class="descriptions">
              Pros
              <li>Great for controlling recoil on single shot firing.</li>
            </ul>
            <ul class="descriptions">
              Cons
              <li>Has little to no effect on recoil for multiple shots.</li>
            </ul>
          <% elsif barrel == "Extended Barrel" %>
            <h4><%= barrel %></h4>
            <ul class="descriptions">
              Pros
              <li>Deal more damage at further ranges.</li>
            </ul>
            <ul class="descriptions">
              Cons
              <li>The damage spike isn't much and it doesn't help your weapon's recoil.</li>
            </ul>
          <% end %>
        <% end %>
      </div>
      <% else %>
      <div id="menu2" class="tab-pane fade">
        <h2>BARREL</h2>
        <h4>No barrel available!</h4>
      </div>
      <% end %>
      <% if @gun.underbarrel %>
      <div id="menu3" class="tab-pane fade">
        <h2>UNDERBARREL</h2>
        <% if @gun.underbarrel == "Laser" %>
          <h4><%= @gun.underbarrel %></h4>
          <ul class="descriptions">
            Pros
            <li>Reduces bullet spread on your weapons.</li>
          </ul>
          <ul class="descriptions">
            Cons
            <li>If you aren't careful, you can be spotted due to your laser.</li>
          </ul>
        <% end %>
      <% else %>
      <div id="menu3" class="tab-pane fade">
        <h2>UNDERBARREL</h2>
        <h4>No underbarrel available!</h4>
      </div>
      <%end%>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Noob Gaming</title>
    <%= csrf_meta_tags %>

    <link rel="icon" href="https://s3.us-east-2.amazonaws.com/noob-gaming-assets/logo.png">
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="<%= body_class %>">
    <div class="circle" onclick="showSideMenu()">
      <h3 id="circleIcon">&rarr;</h3>
    </div>
    <div id="backgroundSideMenu">
      <div id="sideMenu">
        <ul>
          <h3>General</h3>
          <a class="navMenuLinks" href="<%= root_path %>"><li>HOME</li></a>
          <a class="navMenuLinks" href="/about"><li>ABOUT</li></a>
          <br>
          <h3>Rainbow Six Siege</h3>
          <a class="navMenuLinks" href="/siege"><li>MAIN PAGE</li></a>
          <a class="navMenuLinks" href="<%= siege_general_path %>"><li>GENERAL</li></a>
          <a class="navMenuLinks" href="<%= siege_operators_path %>"><li>OPERATORS</li></a>
          <a class="navMenuLinks" href="<%= siege_guns_path %>"><li>GUNS</li></a>
          <br>
          <h3>Bloodborne</h3>
          <a class="navMenuLinks" href="/bloodborne"><li>MAIN PAGE</li></a>
        </ul>
      </div>
      <div class="circleClose" onclick="closeSideMenu()">
        <h3 id="circleCloseIcon">&larr;</h3>
      </div>
    </div>
    <%= yield %>
  </body>
</html>

app/views/operators/_form.html.erb
<%= form_with(model: operator, local: true) do |form| %>
  <% if operator.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(operator.errors.count, "error") %> prohibited this operator from being saved:</h2>

      <ul>
      <% operator.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :pick_rate %>
    <%= form.text_field :pick_rate, id: :operator_pick_rate %>
  </div>

  <div class="field">
    <%= form.label :win_rate %>
    <%= form.text_field :win_rate, id: :operator_win_rate %>
  </div>

  <div class="field">
    <%= form.label :kda %>
    <%= form.text_field :kda, id: :operator_kda %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/operators/edit.html.erb
<h1>Editing Operator</h1>

<%= render 'form', operator: @operator %>

<%= link_to 'Show', @operator %> |
<%= link_to 'Back', operators_path %>

app/views/operators/index.html.erb
<p id="notice"><%= notice %></p>
<div class="searchArea">

</div>
<div class="search">
  <h2>Search By:</h2>
  <div class="ctu">
    <h3>CTU</h3>
    <ul>
      <% @operators.find_by_sql("SELECT DISTINCT organization FROM operators").each do |operator| %>
      <a href="/siege/operators/o/<%= operator.organization %>"><li><%= operator.organization %></li></a>
      <% end %><br />
    </ul>
  </div>
  <div class="role">
    <h3>Role</h3>
    <ul>
      <% @operators.find_by_sql("SELECT DISTINCT main_catagory FROM operators").each do |operator| %>
      <a href="/siege/operators/c/<%= operator.main_catagory %>"><li><%= operator.main_catagory %></li></a>
      <% end %><br />
    </ul>
  </div>
  <div class="speed">
    <h3>Speed</h3>
    <ul>
      <% @operators.find_by_sql("SELECT DISTINCT speed FROM operators ORDER BY speed").each do |operator| %>
      <a href="/siege/operators/s/<%= operator.speed %>"><li><%= operator.speed %> Speed</li></a>
      <% end %><br />
    </ul>
  </div>
  <div class="armor">
    <h3>Armor</h3>
    <ul>
      <% @operators.find_by_sql("SELECT DISTINCT armor FROM operators ORDER BY armor").each do |operator| %>
      <a href="/siege/operators/a/<%= operator.armor %>"><li><%= operator.armor %> Armor</li></a>
      <% end %><br />
    </ul>
  </div>
</div>
<div class="attackers">
  <h2>Attack Operators</h2>
  <% @operators.each do |operator| %>
    <% if operator.role == "Attacker" %>
    <%= link_to siege_operator_path(operator) do %>
      <div class="operator">
        <div class="<%= operator.name %>-badge">
        </div>
          <%= operator.name %><br />
        <%= operator.organization %>
      </div>
      <% end %>
    <% end %>
  <% end %>
</div>
<div class="defenders">
  <h2>Defense Operators</h2>
  <% @operators.each do |operator| %>
    <% if operator.role == "Defender" %>
    <%= link_to siege_operator_path(operator) do %>
      <div class="operator">
        <div class="<%= operator.name %>-badge">
        </div>
          <%= operator.name %><br />
        <%= operator.organization %>
      </div>
      <% end %>
    <% end %>
  <% end %>
</div>

app/views/operators/new.html.erb
<h1>New Operator</h1>

<%= render 'form', operator: @operator %>

<%= link_to 'Back', operators_path %>